require "nokogiri"
require "open-uri"
require "pry"
require_relative "./fine_woodworking/version"
require_relative "./cli"
require_relative "./fine_woodworking/article"
require_relative "./fine_woodworking/scraper"
